name: planify
description: Simple MVP version with Dashboard, Focus Timer, Settings
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.3
  firebase_core: ^2.25.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  google_sign_in: ^6.1.5
  firebase_messaging: ^14.9.0

flutter:
  uses-material-design: true
